version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: db-chapters
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
